const defaults=[{id:1,name:'Morning meditation',category:'Mind',icon:'☼',color:'#e6e0fa',checks:[],repeat:'daily',days:[],reminder:''},{id:2,name:'Read 20 pages',category:'Growth',icon:'▤',color:'#dcefe8',checks:[],repeat:'daily',days:[],reminder:''},{id:3,name:'Move my body',category:'Health',icon:'⌁',color:'#fde5e0',checks:[],repeat:'daily',days:[],reminder:''},{id:4,name:'Drink 8 glasses of water',category:'Health',icon:'◈',color:'#dcecf9',checks:[],repeat:'daily',days:[],reminder:''}];
const today=new Date(),habitKey='flowin-habits-v1',accountKey='flowin-account-v1',reminderKey='flowin-reminders-v1';
let habits=JSON.parse(localStorage.getItem(habitKey)||'null')||defaults,selectedColor='#7567e8',isLogin=false,selectedDays=[];
const $=s=>document.querySelector(s),dateKey=d=>{d=new Date(d);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`},todayKey=dateKey(today);
const icons={Mind:'☼',Growth:'▤',Health:'⌁',Home:'⌂'};
const quotes=[['The secret of getting ahead is getting started.','— Mark Twain'],['Little by little, a little becomes a lot.','— Tanzanian proverb'],['You do not have to be great to start, but you have to start to be great.','— Zig Ziglar'],['Discipline is choosing between what you want now and what you want most.','— Abraham Lincoln'],['Every action you take is a vote for the person you wish to become.','— James Clear'],['Success is the sum of small efforts, repeated day in and day out.','— Robert Collier']];
const done=(h,d=todayKey)=>h.checks.includes(d);
const scheduled=(h,d=new Date())=>h.repeat!=='custom'||(h.days||[]).includes(d.getDay());
function save(){localStorage.setItem(habitKey,JSON.stringify(habits))}
function streak(h){let n=0,d=new Date(today);while(done(h,dateKey(d))){n++;d.setDate(d.getDate()-1)}return n}
function repeatLabel(h){return h.repeat==='daily'?'Every day':(h.days||[]).map(d=>['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][d]).join(', ')}
function toggle(id){let h=habits.find(x=>x.id===id);h.checks=done(h)?h.checks.filter(d=>d!==todayKey):[...h.checks,todayKey];save();render()}
function removeHabit(id){let h=habits.find(x=>x.id===id);if(h&&confirm(`Delete “${h.name}”? This cannot be undone.`)){habits=habits.filter(x=>x.id!==id);save();render()}}
function render(){let active=habits.filter(h=>scheduled(h)),completed=active.filter(h=>done(h)).length,pct=active.length?Math.round(completed/active.length*100):0;
  $('#progressText').textContent=`${completed} of ${active.length} complete`;$('#progressPercent').textContent=pct+'%';$('#progressRing').style.background=`conic-gradient(#f59e0b ${pct}%,#ffe0ad 0)`;$('#progressMessage').textContent=pct===100&&active.length?'Beautiful work — you did it!':pct?'You’re building momentum.':active.length?'A fresh page. Let’s begin.':'Nothing scheduled for today.';
  $('#habitList').innerHTML=habits.map(h=>`<article class="habit-card ${done(h)?'completed':''} ${scheduled(h)?'':'not-today'}"><div class="habit-icon" style="background:${h.color}">${h.icon}</div><div><div class="habit-name">${h.name}</div><div class="habit-meta">${repeatLabel(h)}${h.reminder?' · ⏰ '+h.reminder:''}</div></div><span class="streak">🔥 ${streak(h)} day streak</span><button class="delete-habit" title="Delete habit" data-delete="${h.id}">×</button><button class="check-button" aria-label="Complete ${h.name}" data-id="${h.id}">${done(h)?'✓':''}</button></article>`).join('')||'<p>No habits yet. Create one to begin your journey.</p>';
  document.querySelectorAll('.check-button').forEach(b=>b.onclick=()=>toggle(+b.dataset.id));document.querySelectorAll('.delete-habit').forEach(b=>b.onclick=()=>removeHabit(+b.dataset.delete));renderWeek();renderInsights();renderHeatmap()}
function renderWeek(){let total=0,possible=0,html='';for(let i=6;i>=0;i--){let d=new Date(today);d.setDate(d.getDate()-i);let active=habits.filter(h=>scheduled(h,d)),n=active.filter(h=>done(h,dateKey(d))).length;total+=n;possible+=active.length;html+=`<div class="day-bar ${i===0?'today':''}"><div class="bar-track"><div class="bar-fill" style="height:${active.length?n/active.length*100:0}%"></div></div><span>${i===0?'Today':d.toLocaleDateString('en',{weekday:'short'})}</span></div>`}$('#weekChart').innerHTML=html;$('#weekScore').textContent=(possible?Math.round(total/possible*100):0)+'%';let best=Math.max(0,...habits.map(streak)),champ=[...habits].sort((a,b)=>streak(b)-streak(a))[0];$('#bestStreak').textContent=best+' day'+(best===1?'':'s');$('#streakHabit').textContent=champ&&best?`${champ.name} is your current rhythm.`:'Start your first habit today.'}
function renderInsights(){let n=habits.reduce((sum,h)=>sum+h.checks.length,0),best=Math.max(0,...habits.map(streak));$('#insightGrid').innerHTML=`<article><span class="tiny-label">ALL-TIME CHECK-INS</span><strong>${n}</strong><p>Every one is progress.</p></article><article><span class="tiny-label">CURRENT BEST STREAK</span><strong>${best} days</strong><p>Consistency looks good on you.</p></article><article><span class="tiny-label">ACTIVE HABITS</span><strong>${habits.length}</strong><p>Your personal rituals.</p></article>`}
function renderHeatmap(){let year=today.getFullYear(),start=new Date(year,0,1),first=new Date(start);first.setDate(start.getDate()-start.getDay());let html='<div class="weekday-labels"><span>Sun</span><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span></div><div class="heatmap-content"><div class="month-labels">';for(let w=0;w<53;w++){let d=new Date(first);d.setDate(first.getDate()+w*7);html+=d.getDate()<=7?`<span style="grid-column:${w+1}">${d.toLocaleDateString('en',{month:'short'})}</span>`:'<span></span>'}html+='</div><div class="heatmap-cells">';for(let w=0;w<53;w++)for(let day=0;day<7;day++){let d=new Date(first);d.setDate(first.getDate()+w*7+day);let count=d.getFullYear()===year?habits.filter(h=>done(h,dateKey(d))).length:0,level=count?Math.min(4,Math.ceil(count/Math.max(1,habits.length)*4)):0;html+=`<i class="heat-day level-${level}" title="${d.toLocaleDateString('en',{month:'short',day:'numeric'})}: ${count} completed"></i>`}html+='</div></div>';$('#yearHeatmap').innerHTML=html;let total=habits.reduce((n,h)=>n+h.checks.filter(d=>d.startsWith(year+'-')).length,0);$('#activityTotal').textContent=total+' check-in'+(total===1?'':'s')}
function showQuote(){let q=quotes[Math.floor(Math.random()*quotes.length)];$('#quoteText').textContent=q[0];$('#quoteAuthor').textContent=q[1]}
function scheduleReminders(){let timers=JSON.parse(localStorage.getItem(reminderKey)||'{}');Object.values(timers).forEach(clearTimeout);timers={};habits.filter(h=>h.reminder&&scheduled(h)).forEach(h=>{let [hour,min]=h.reminder.split(':').map(Number),when=new Date();when.setHours(hour,min,0,0);if(when<=new Date())return;timers[h.id]=setTimeout(()=>{if(!done(h)&&'Notification'in window&&Notification.permission==='granted')new Notification('Flowin reminder',{body:`Time for ${h.name} ✦`});},when-Date.now())});localStorage.setItem(reminderKey,JSON.stringify(timers))}
function setAuthMode(login){isLogin=login;$('#authTitle').textContent=login?'Welcome back.':'Make it official.';$('#authSubtitle').textContent=login?'Pick up where your intentions left off.':'Your next chapter starts with one small ritual.';$('#authSubmit').textContent=login?'Log in to Flowin':'Create my account';$('#nameField').style.display='block';$('#authSwitch').innerHTML=login?'New to Flowin? <button type="button" id="switchAuth">Create an account</button>':'Already have an account? <button type="button" id="switchAuth">Log in</button>';$('#switchAuth').onclick=()=>setAuthMode(!isLogin)}
function enterApp(account){$('#authScreen').classList.add('hidden');$('#userAvatar').textContent=account.name[0].toUpperCase();showQuote();scheduleReminders()}
document.querySelectorAll('.nav-link[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-link').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(x=>x.classList.remove('active-view'));$('#'+b.dataset.view).classList.add('active-view');$('#pageTitle').textContent=b.dataset.view==='today'?'Make today count.':'See your growth.'});
$('#authForm').onsubmit=e=>{e.preventDefault();let name=$('#authName').value.trim(),password=$('#authPassword').value;if(!name)return $('#authName').focus();if(isLogin){let a=JSON.parse(localStorage.getItem(accountKey)||'null');if(!a||a.name.toLowerCase()!==name.toLowerCase()||a.password!==password)return alert('We could not find that name and password combination.');enterApp(a)}else{let a={name,password};localStorage.setItem(accountKey,JSON.stringify(a));enterApp(a)}};
$('#dateLabel').textContent=today.toLocaleDateString('en',{weekday:'long',month:'long',day:'numeric'}).toUpperCase();$('#openHabitModal').onclick=()=>$('#habitModal').showModal();$('#habitCategory').onchange=()=>$('#customCategoryField').classList.toggle('show',$('#habitCategory').value==='custom');
$('#habitRepeat').onchange=()=>$('#dayPicker').style.display=$('#habitRepeat').value==='custom'?'flex':'none';document.querySelectorAll('#dayPicker button').forEach(b=>b.onclick=()=>{let d=+b.dataset.day;if(selectedDays.includes(d)){selectedDays=selectedDays.filter(x=>x!==d);b.style.background='';b.style.color=''}else{selectedDays.push(d);b.style.background='#6e5ce7';b.style.color='#fff'}});
$('#habitForm').addEventListener('submit',async e=>{if(e.submitter.value==='cancel')return;let name=$('#habitName').value.trim(),category=$('#habitCategory').value,repeat=$('#habitRepeat').value,reminder=$('#reminderTime').value;if(!name)return;e.preventDefault();if(category==='custom'){category=$('#customCategory').value.trim();if(!category)return $('#customCategory').focus()}if(repeat==='custom'&&!selectedDays.length)return alert('Choose at least one day.');if(reminder&&'Notification'in window&&Notification.permission==='default')await Notification.requestPermission();let palette={'#7567e8':'#e6e0fa','#e07593':'#f8e0e8','#e8a44c':'#fbe9cc','#55a990':'#dcefe8'};habits.push({id:Date.now(),name,category,icon:icons[category]||'✦',color:palette[selectedColor],checks:[],repeat,days:repeat==='custom'?selectedDays:[],reminder});save();$('#habitModal').close();e.target.reset();selectedDays=[];document.querySelectorAll('#dayPicker button').forEach(b=>{b.style.background='';b.style.color=''});$('#dayPicker').style.display='none';$('#customCategoryField').classList.remove('show');render();scheduleReminders()});
document.querySelectorAll('.color-choice').forEach(c=>c.onclick=()=>{selectedColor=c.dataset.color;document.querySelectorAll('.color-choice').forEach(x=>x.classList.remove('selected'));c.classList.add('selected')});$('#themeButton').onclick=()=>document.body.classList.toggle('dark');$('.mobile-menu').onclick=()=>$('.sidebar').classList.toggle('show');$('#logoutButton').onclick=()=>{$('#authForm').reset();setAuthMode(true);$('#authScreen').classList.remove('hidden')};let existing=JSON.parse(localStorage.getItem(accountKey)||'null');if(existing)enterApp(existing);render();
