const compassKey='flowin-daily-compass-v1';
let compass=JSON.parse(localStorage.getItem(compassKey)||'null')||{};
function saveCompass(){localStorage.setItem(compassKey,JSON.stringify(compass))}
function dayCompass(){const key=dateKey(today);if(compass.day!==key)compass={day:key,mood:null,focusSeconds:0,starterDone:false};return compass}
function moodCopy(mood){
  return({great:['You have momentum—choose a quest that matters.','Take on a focused quest while your energy is high.'],good:['A steady day is a strong day.','Pick one meaningful quest and let it be enough.'],neutral:['No need to force a big win.','Try the two-minute version of one quest.'],low:['Today can be gentle and still count.','Choose a tiny quest. Showing up is the win.'],tired:['Rest is part of the campaign.','Try a small reset, then decide what feels possible.']})[mood]||['Meet yourself where you are.','Choose one quest that feels kind and possible.']
}
function renderCompass(){
  const data=dayCompass();let box=$('#dailyCompass');if(!box){box=document.createElement('section');box.id='dailyCompass';box.className='compass-section';$('.hero-grid').insertAdjacentElement('afterend',box)}
  const copy=moodCopy(data.mood),mins=Math.floor(data.focusSeconds/60),secs=data.focusSeconds%60;
  box.innerHTML='<article class="compass-card"><div class="compass-header"><div><span class="tiny-label">DAILY COMPASS</span><h2>'+copy[0]+'</h2><p>'+copy[1]+'</p></div><span class="compass-star">✦</span></div><div class="mood-line"><span>How are you arriving today?</span><div>'+[['great','😄'],['good','🙂'],['neutral','😐'],['low','😞'],['tired','😫']].map(m=>'<button class="'+(data.mood===m[0]?'picked':'')+'" data-mood="'+m[0]+'" aria-label="I feel '+m[0]+'">'+m[1]+'</button>').join('')+'</div></div><div class="compass-actions"><button class="starter '+(data.starterDone?'done':'')+'" id="starterQuest">'+(data.starterDone?'✓ Tiny reset complete':'✦ Complete a 2-minute reset')+'</button><div class="focus-box"><span class="tiny-label">FLOW SPRINT</span><strong id="focusTimer">'+String(mins).padStart(2,'0')+':'+String(secs).padStart(2,'0')+'</strong><button id="focusButton">'+(data.focusSeconds?'Pause':'Start 10 min')+'</button></div></div></article>';
  document.querySelectorAll('[data-mood]').forEach(b=>b.onclick=()=>{data.mood=b.dataset.mood;saveCompass();renderCompass()});
  $('#starterQuest').onclick=()=>{if(!data.starterDone){data.starterDone=true;game.coins=(game.coins||0)+3;saveCompass();saveGame();renderCompass();renderGame()}};
  $('#focusButton').onclick=()=>startFocus(data);
}
let focusInterval=null;
function startFocus(data){if(focusInterval){clearInterval(focusInterval);focusInterval=null;renderCompass();return}if(!data.focusSeconds)data.focusSeconds=600;focusInterval=setInterval(()=>{data.focusSeconds--;saveCompass();const timer=$('#focusTimer');if(timer)timer.textContent=String(Math.floor(data.focusSeconds/60)).padStart(2,'0')+':'+String(data.focusSeconds%60).padStart(2,'0');if(data.focusSeconds<=0){clearInterval(focusInterval);focusInterval=null;game.coins=(game.coins||0)+5;saveGame();renderCompass();renderGame();alert('Flow sprint complete! You earned 5 coins.')}},1000);renderCompass()}
const flowStyle=document.createElement('style');
flowStyle.textContent='.compass-section{margin:25px 0}.compass-card{border-radius:18px;padding:20px 23px;background:linear-gradient(115deg,#192e43,#264f5c);color:#fff;box-shadow:0 15px 30px #17304424}.compass-header{display:flex;justify-content:space-between;gap:20px}.compass-card .tiny-label{color:#b8e9e0}.compass-card h2{font-size:22px;margin-top:4px}.compass-card p{color:#d3e5e7}.compass-star{font-size:31px;color:#f7cf66}.mood-line{display:flex;align-items:center;justify-content:space-between;gap:15px;margin-top:18px;color:#c2d6dc;font-size:12px;font-weight:700}.mood-line div{display:flex;gap:7px}.mood-line button{width:31px;height:31px;border-radius:50%;background:#ffffff20;font-size:16px}.mood-line button.picked{outline:2px solid #66e1ca;background:#ffffff3d}.compass-actions{margin-top:17px;display:flex;align-items:center;justify-content:space-between;gap:14px}.starter{background:#d8fff4;color:#1d5a55;border-radius:9px;padding:10px 12px;font-size:12px;font-weight:800}.starter.done{background:#4dbda6;color:#fff}.focus-box{display:flex;align-items:center;gap:9px;background:#ffffff12;padding:7px 8px 7px 11px;border-radius:9px}.focus-box strong{font-size:14px}.focus-box .tiny-label{font-size:8px}.focus-box button{background:#79d8d0;color:#153a43;border-radius:7px;padding:7px 8px;font-size:11px;font-weight:800}@media(max-width:760px){.compass-card{padding:18px}.mood-line,.compass-actions{align-items:flex-start;flex-direction:column}.mood-line div{width:100%;justify-content:space-between}.mood-line button{width:36px;height:36px}.focus-box{width:100%;justify-content:space-between}}';
document.head.appendChild(flowStyle);
renderCompass();
