const petKey='flowin-pets-v1';
let petState=JSON.parse(localStorage.getItem(petKey)||'null')||{owned:[],active:null};
const petCatalog={dog:{name:'Dog',icon:'🐶',price:80},cat:{name:'Cat',icon:'🐱',price:110},dragon:{name:'Dragon',icon:'🐲',price:300}};
function savePets(){localStorage.setItem(petKey,JSON.stringify(petState))}
function petLevel(pet){return Math.floor(pet.xp/50)+1}
function petStage(pet){const l=petLevel(pet);return l>=12?'Legendary':l>=8?'Adult':l>=4?'Young':l>=2?'Baby':'Egg'}
function activePet(){return petState.owned.find(p=>p.id===petState.active)}
function petFace(pet){return!pet||petStage(pet)==='Egg'?'🥚':petCatalog[pet.type].icon}
function buyPet(type){const item=petCatalog[type];if((game.coins||0)<item.price)return alert('You need '+(item.price-(game.coins||0))+' more coins for this companion.');if(petState.owned.some(p=>p.type===type))return;game.coins-=item.price;const pet={id:Date.now(),type,name:item.name,xp:0,accessory:'✨'};petState.owned.push(pet);petState.active=pet.id;saveGame();savePets();renderGame();renderPets()}
function shopMarkup(){return Object.entries(petCatalog).map(x=>'<article><span>'+x[1].icon+'</span><h3>'+x[1].name+'</h3><p>A loyal '+x[1].name.toLowerCase()+' companion.</p><button data-buy="'+x[0]+'">Adopt · 🪙 '+x[1].price+'</button></article>').join('')}
function renderPets(){let section=$('#petSection');if(!section){section=document.createElement('section');section.id='petSection';section.className='pet-section';$('.rpg-section').insertAdjacentElement('afterend',section)}const active=activePet();if(!active){section.innerHTML='<div class="section-heading"><div><h2>Companion stable</h2><p>Spend your quest coins on a companion who grows beside you.</p></div><span class="pet-coin">🪙 '+(game.coins||0)+'</span></div><div class="pet-shop">'+shopMarkup()+'</div>'}else{const level=petLevel(active),progress=active.xp%50,stage=petStage(active),mood=game.energy>70?'Joyful':game.energy>35?'Calm':'Sleepy';section.innerHTML='<div class="section-heading"><div><h2>Your companion</h2><p>Every quest helps your friend grow.</p></div><span class="pet-coin">🪙 '+(game.coins||0)+'</span></div><article class="pet-card"><div class="pet-orb"><span>'+petFace(active)+'</span><i>'+active.accessory+'</i></div><div class="pet-info"><span class="tiny-label">'+stage.toUpperCase()+' COMPANION</span><h2>'+active.name+' <small>Lv. '+level+'</small></h2><p>Mood: <b>'+mood+'</b> · '+active.xp+' total pet XP</p><div class="pet-meter"><i style="width:'+(progress*2)+'%"></i></div><span class="pet-next">'+(50-progress)+' XP to next level</span></div><div class="pet-actions"><button id="renamePet">Rename</button><button class="'+(active.accessory==='👑'?'selected':'')+'" data-accessory="👑" '+(level<4?'disabled':'')+'>👑 Crown</button><button class="'+(active.accessory==='🎀'?'selected':'')+'" data-accessory="🎀">🎀 Bow</button></div></article><div class="pet-roster">'+petState.owned.map(p=>'<button class="'+(p.id===active.id?'active':'')+'" data-equip="'+p.id+'">'+petFace(p)+' '+p.name+'</button>').join('')+'</div>'}document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>buyPet(b.dataset.buy));document.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>{petState.active=+b.dataset.equip;savePets();renderPets()});document.querySelectorAll('[data-accessory]').forEach(b=>b.onclick=()=>{active.accessory=b.dataset.accessory;savePets();renderPets()});const rename=$('#renamePet');if(rename)rename.onclick=()=>{let name=prompt('Give your companion a name:',active.name);if(name&&name.trim()){active.name=name.trim().slice(0,18);savePets();renderPets()}}}
const questCompleteToggle=toggle;
toggle=function(id){const h=habits.find(x=>x.id===id),wasDone=done(h);questCompleteToggle(id);if(!wasDone){const pet=activePet();if(pet){pet.xp+=8;savePets()}}renderPets()};
const gameRenderWithPets=renderGame;
renderGame=function(){gameRenderWithPets();renderPets()};
renderPets();
const petStyle=document.createElement('style');
petStyle.textContent='.pet-section{margin-top:36px}.pet-coin{background:#fff3ca;color:#805b20;padding:7px 10px;border-radius:9px;font-size:12px;font-weight:800}.pet-shop{display:grid;grid-template-columns:repeat(3,1fr);gap:15px}.pet-shop article{background:#fff;border:1px solid #e8e4f0;border-radius:16px;padding:20px;text-align:center;box-shadow:0 10px 25px #41345212}.pet-shop article>span{font-size:42px}.pet-shop h3{margin:9px 0 0;font-family:Fraunces,serif}.pet-shop p{font-size:12px}.pet-shop button,.pet-actions button,.pet-roster button{margin-top:13px;background:#6253dc;color:#fff;border-radius:8px;padding:8px 10px;font-size:12px;font-weight:700}.pet-card{display:grid;grid-template-columns:auto 1fr auto;gap:22px;align-items:center;padding:22px;border:1px solid #e8e4f0;border-radius:18px;background:linear-gradient(120deg,#fffdf9,#f2ecff);box-shadow:0 12px 30px #463a6410}.pet-orb{width:100px;height:100px;display:grid;place-items:center;border-radius:50%;background:radial-gradient(circle at 35% 25%,#fff,#e1d4ff);font-size:52px;position:relative}.pet-orb i{position:absolute;right:-1px;top:-5px;font-style:normal;font-size:23px}.pet-info h2{margin-top:4px}.pet-info h2 small{font-family:DM Sans,sans-serif;font-size:13px;color:#7a708b}.pet-info b{color:#35805a}.pet-meter{height:9px;background:#e4dfee;border-radius:9px;overflow:hidden;margin-top:10px}.pet-meter i{display:block;height:100%;background:linear-gradient(90deg,#f0a94c,#ec6fab);border-radius:9px}.pet-next{font-size:11px;color:#837c8b}.pet-actions{display:grid;gap:7px}.pet-actions button{margin:0;background:#eeeaf7;color:#5e5770}.pet-actions button.selected{background:#755fe0;color:#fff}.pet-actions button:disabled{opacity:.45}.pet-roster{display:flex;gap:8px;margin-top:12px}.pet-roster button{margin:0;background:#eeeaf7;color:#5e5770}.pet-roster button.active{background:#6b5ae3;color:#fff}@media(max-width:760px){.pet-shop{grid-template-columns:1fr}.pet-card{grid-template-columns:auto 1fr;gap:15px}.pet-actions{grid-column:1/-1;display:flex}.pet-actions button{flex:1}.pet-orb{width:76px;height:76px;font-size:40px}}';
document.head.appendChild(petStyle);
